version: '3.8'

services:
  api:
    build:
      context: ./api
      target: develop
    volumes:
      - ./:/project:delegated
    ports:
      - 50000:3000
    environment:
      - INCOMMING_WEB_HOOK=${INCOMMING_WEB_HOOK}
      - GCP_KEY_FILENAME=${GCP_KEY_FILENAME}
  slack-event-handler:
    build:
      context: ./slack-event-handler
      target: develop
    volumes:
      - ./:/project:delegated
    ports:
      - 50010:3000
  app:
    build:
      context: ./app
      target: develop
    volumes:
      - ./:/project:delegated
    ports:
      - 50100:3000
