name: unit-test
on: [push]
jobs:
  api:
    runs-on: ubuntu-latest
    container: node:16-slim
    steps:
      - uses: actions/checkout@v2
      - working-directory: ./api
        run: npm ci  && npm test
